### ISSUE TITLE
A thought on naming

### ISSUE THREAD

**Issue by tomchristie** [python-http/python-http.org#3]
One of the difficulties with the existing `http3` project is that it's really clear that it just doesn't have the right name yet. We've got `https` available to us, but I'm not sure that *any* acronym actually ends up making for a good project name. (Eg. there's no good way to talk about the project in prose documentation, or when referring to it.)

Having thought and searched around, really haven't seen many nice thematically linked names that'd work well for it.

One possible option that occurred to me is picking up where @lukasa's "hyper" left off ~3 years, ago? https://github.com/Lukasa/hyper

It's a really decent name, but the project is basically discontinued right now.
A 0.8 release of "hyper", under a completely revamped API & implementation might be a go-er?

Any thoughts? Good alternatives? Worth reaching out to Cory for discussion?

**Comment by sethmlarson** [comment]
I do love the name "hyper" however that project has an existing user-base (~2K downloads per day). If we released a breaking change it wouldn't be the end of the world but it's something we'd have to handle and make clear to users somehow.

There's a package called `fetch` that is version `0.0` that receives barely a download per day that we could potentially ask the PyPA to release to us? I'll keep looking for other names too.

**Comment by tomchristie** [comment]
> I do love the name "hyper" however that project has an existing user-base (~2K downloads per day). If we released a breaking change it wouldn't be the end of the world but it's something we'd have to handle and make clear to users somehow.

Gotcha - I guess it may be worth navigating that, for the sake of ending up with a really strong brand we can get behind. It's also a bit complicated by the "hyper" organisation, which already isn't clearly seperated from the "hyper" library.

Eg. These two RTD pages are already a bit confusing for newcomers, as they currently stand:

* https://python-hyper.org/en/latest/
* https://hyper.readthedocs.io/en/latest/

I think if we wanted to look into the viability of that route, we'd probably also need to make sure we've got a clear plan for what 

Personally I think it'd be a pretty strong story if a bunch of the dependencies currently under "hyper" came under "python-http" instead, and if we rejuvenated the "hyper" project with a re-release based on the https://github.com/encode/http3/ codebase

Options wrt. compat would be either:

* Include an `HTTPConnection` class which simply errors when instantiated with a "Pin your dependencies, kiddo 💙" message, and links to appropriate release notes about how and why the new version isn't API compatible.
* Include an `HTTPConnection` class and endevour to provide backwards-compat API against it, using the new internals. (Perhaps with a view to deprecating bits of that for the 1.0 release?)

Obvs getting ahead of things there - haven't even solicited Cory's thoughts on any of this yet, but I *do* think it'd be a super-strong brand to have as the top-level client lib that ties the lower-level sans-io parts together.

**Comment by tomchristie** [comment]
I think it'd be too early to commit to, but worth exploring maybe.

And yeah, then `fetch` name could defo. work too. I don't think it's quite as strong, but it's obvs. got less baggage.

**Comment by sethmlarson** [comment]
Let's move this discussion into a team discussion so it's more visible?

**Comment by sethmlarson** [comment]
I opened up a thread: https://github.com/orgs/python-http/teams/members/discussions/1

**Comment by N-Coder** [comment]
Unfortunately, that link doesn't work for non-members of the team, so it is actually less visible to the general public. :/
I'm very interested in following the development of this part of the python ecosystem, so it would be cool if you could keep those discussions open. ;)

Sidenote: the ["Members" section on the website](https://python-http.org/#membership) links to a pretty empty GitHub page telling you that the organization has no public members.

**Comment by tomchristie** [comment]
I guess public discussions should either occur here, or there could be a `discussions` repo, that's purely for that purpose.

**Comment by sethmlarson** [comment]
That seems strange why that discussion wouldn't be public? I have all visibilities set to 'Visible' and not 'Secret'? Maybe it has something to do with all of us having our Org Visibility set to Private?

**Comment by tomchristie** [comment]
GitHub's wording doesn't make it super obvious but Team Discussions are either restricted to being "visible" to org members, or "private" to team members only.

I don't think there's any setting for "public" to the whole world.

 https://github.blog/2017-11-20-introducing-team-discussions/#chat-with-your-team-in-public-or-private

**Comment by sethmlarson** [comment]
Yep, that's just what I saw as well. I created the python-http/discussions repository and migrated all existing team discussions with comments into public view. :)
